spring:
  application:
    name: ai-service-client
  config:
    import: optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true  # 启用服务发现，注册到 Nacos
      config:
        server-addr: localhost:8848
        enabled: false  # 如果不需要配置中心，可以禁用

  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 300MB  # 单个文件最大 300MB
      max-request-size: 300MB  # 整个请求最大 300MB

server:
  port: 0  # 随机端口，后续自行调整



# AI 服务配置
ai:
  service:
    base-url: http://localhost:8001
